package net.minecraft;

import com.google.common.collect.ImmutableMap;
import com.google.common.collect.Maps;
import com.google.common.collect.ImmutableMap.Builder;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.client.model.ModelPart;
import net.minecraft.client.render.block.entity.BannerBlockEntityRenderer;
import net.minecraft.client.render.block.entity.BedBlockEntityRenderer;
import net.minecraft.client.render.block.entity.BellBlockEntityRenderer;
import net.minecraft.client.render.block.entity.ChestBlockEntityRenderer;
import net.minecraft.client.render.block.entity.ConduitBlockEntityRenderer;
import net.minecraft.client.render.block.entity.SignBlockEntityRenderer;
import net.minecraft.client.render.entity.EndCrystalEntityRenderer;
import net.minecraft.client.render.entity.EnderDragonEntityRenderer;
import net.minecraft.client.render.entity.WitherSkullEntityRenderer;
import net.minecraft.client.render.entity.feature.TridentRiptideFeatureRenderer;
import net.minecraft.client.render.entity.model.ArmorStandEntityModel;
import net.minecraft.client.render.entity.model.BatEntityModel;
import net.minecraft.client.render.entity.model.BeeEntityModel;
import net.minecraft.client.render.entity.model.BipedEntityModel;
import net.minecraft.client.render.entity.model.BlazeEntityModel;
import net.minecraft.client.render.entity.model.BoatEntityModel;
import net.minecraft.client.render.entity.model.BookModel;
import net.minecraft.client.render.entity.model.ChickenEntityModel;
import net.minecraft.client.render.entity.model.CodEntityModel;
import net.minecraft.client.render.entity.model.CowEntityModel;
import net.minecraft.client.render.entity.model.CreeperEntityModel;
import net.minecraft.client.render.entity.model.DolphinEntityModel;
import net.minecraft.client.render.entity.model.DonkeyEntityModel;
import net.minecraft.client.render.entity.model.DragonHeadEntityModel;
import net.minecraft.client.render.entity.model.DrownedEntityModel;
import net.minecraft.client.render.entity.model.ElytraEntityModel;
import net.minecraft.client.render.entity.model.EndermanEntityModel;
import net.minecraft.client.render.entity.model.EndermiteEntityModel;
import net.minecraft.client.render.entity.model.EntityModelLayer;
import net.minecraft.client.render.entity.model.EntityModelLayers;
import net.minecraft.client.render.entity.model.EvokerFangsEntityModel;
import net.minecraft.client.render.entity.model.FoxEntityModel;
import net.minecraft.client.render.entity.model.GhastEntityModel;
import net.minecraft.client.render.entity.model.GuardianEntityModel;
import net.minecraft.client.render.entity.model.HoglinEntityModel;
import net.minecraft.client.render.entity.model.HorseEntityModel;
import net.minecraft.client.render.entity.model.IllagerEntityModel;
import net.minecraft.client.render.entity.model.IronGolemEntityModel;
import net.minecraft.client.render.entity.model.LargePufferfishEntityModel;
import net.minecraft.client.render.entity.model.LargeTropicalFishEntityModel;
import net.minecraft.client.render.entity.model.LeashKnotEntityModel;
import net.minecraft.client.render.entity.model.LlamaEntityModel;
import net.minecraft.client.render.entity.model.LlamaSpitEntityModel;
import net.minecraft.client.render.entity.model.MagmaCubeEntityModel;
import net.minecraft.client.render.entity.model.MediumPufferfishEntityModel;
import net.minecraft.client.render.entity.model.MinecartEntityModel;
import net.minecraft.client.render.entity.model.OcelotEntityModel;
import net.minecraft.client.render.entity.model.PandaEntityModel;
import net.minecraft.client.render.entity.model.ParrotEntityModel;
import net.minecraft.client.render.entity.model.PhantomEntityModel;
import net.minecraft.client.render.entity.model.PigEntityModel;
import net.minecraft.client.render.entity.model.PiglinEntityModel;
import net.minecraft.client.render.entity.model.PlayerEntityModel;
import net.minecraft.client.render.entity.model.PolarBearEntityModel;
import net.minecraft.client.render.entity.model.RabbitEntityModel;
import net.minecraft.client.render.entity.model.RavagerEntityModel;
import net.minecraft.client.render.entity.model.SalmonEntityModel;
import net.minecraft.client.render.entity.model.SheepEntityModel;
import net.minecraft.client.render.entity.model.SheepWoolEntityModel;
import net.minecraft.client.render.entity.model.ShieldEntityModel;
import net.minecraft.client.render.entity.model.ShulkerBulletEntityModel;
import net.minecraft.client.render.entity.model.ShulkerEntityModel;
import net.minecraft.client.render.entity.model.SilverfishEntityModel;
import net.minecraft.client.render.entity.model.SkeletonEntityModel;
import net.minecraft.client.render.entity.model.SkullEntityModel;
import net.minecraft.client.render.entity.model.SlimeEntityModel;
import net.minecraft.client.render.entity.model.SmallPufferfishEntityModel;
import net.minecraft.client.render.entity.model.SmallTropicalFishEntityModel;
import net.minecraft.client.render.entity.model.SnowGolemEntityModel;
import net.minecraft.client.render.entity.model.SpiderEntityModel;
import net.minecraft.client.render.entity.model.SquidEntityModel;
import net.minecraft.client.render.entity.model.StriderEntityModel;
import net.minecraft.client.render.entity.model.TridentEntityModel;
import net.minecraft.client.render.entity.model.TurtleEntityModel;
import net.minecraft.client.render.entity.model.VexEntityModel;
import net.minecraft.client.render.entity.model.VillagerResemblingModel;
import net.minecraft.client.render.entity.model.WitchEntityModel;
import net.minecraft.client.render.entity.model.WitherEntityModel;
import net.minecraft.client.render.entity.model.WolfEntityModel;
import net.minecraft.client.render.entity.model.ZombieVillagerEntityModel;
import net.minecraft.entity.vehicle.BoatEntity;
import net.minecraft.util.SignType;

@Environment(EnvType.CLIENT)
public class class_5600 {
	private static final class_5605 field_27543 = new class_5605(0.008F);
	private static final class_5605 field_27544 = new class_5605(1.0F);
	private static final class_5605 field_27545 = new class_5605(0.5F);

	public static Map<EntityModelLayer, ModelPart> method_32073() {
		Builder<EntityModelLayer, class_5607> builder = ImmutableMap.builder();
		class_5607 lv = class_5607.method_32110(BipedEntityModel.method_32011(class_5605.field_27715, 0.0F), 64, 64);
		class_5607 lv2 = class_5607.method_32110(BipedEntityModel.method_32011(field_27544, 0.0F), 64, 32);
		class_5607 lv3 = class_5607.method_32110(BipedEntityModel.method_32011(new class_5605(1.02F), 0.0F), 64, 32);
		class_5607 lv4 = class_5607.method_32110(BipedEntityModel.method_32011(field_27545, 0.0F), 64, 32);
		class_5607 lv5 = MinecartEntityModel.method_32020();
		class_5607 lv6 = SkullEntityModel.method_32050();
		class_5607 lv7 = class_5607.method_32110(HorseEntityModel.method_32010(class_5605.field_27715), 64, 64);
		class_5607 lv8 = IllagerEntityModel.method_32012();
		class_5607 lv9 = CowEntityModel.method_31990();
		class_5607 lv10 = class_5607.method_32110(OcelotEntityModel.method_32021(class_5605.field_27715), 64, 32);
		class_5607 lv11 = class_5607.method_32110(PiglinEntityModel.method_32026(class_5605.field_27715), 64, 64);
		class_5607 lv12 = SkullEntityModel.method_32049();
		class_5607 lv13 = LlamaEntityModel.method_32018(class_5605.field_27715);
		class_5607 lv14 = StriderEntityModel.method_32058();
		class_5607 lv15 = HoglinEntityModel.method_32009();
		class_5607 lv16 = SkeletonEntityModel.method_32047();
		class_5607 lv17 = class_5607.method_32110(VillagerResemblingModel.method_32064(), 64, 64);
		class_5607 lv18 = SpiderEntityModel.method_32054();
		builder.put(EntityModelLayers.ARMOR_STAND, ArmorStandEntityModel.method_31979());
		builder.put(EntityModelLayers.ARMOR_STAND_INNER_ARMOR, lv4);
		builder.put(EntityModelLayers.ARMOR_STAND_OUTER_ARMOR, lv2);
		builder.put(EntityModelLayers.BANNER, BannerBlockEntityRenderer.method_32135());
		builder.put(EntityModelLayers.BAT, BatEntityModel.method_31980());
		builder.put(EntityModelLayers.BED_FOOT, BedBlockEntityRenderer.method_32137());
		builder.put(EntityModelLayers.BED_HEAD, BedBlockEntityRenderer.method_32136());
		builder.put(EntityModelLayers.BEE, BeeEntityModel.method_31981());
		builder.put(EntityModelLayers.BELL, BellBlockEntityRenderer.method_32138());
		builder.put(EntityModelLayers.BLAZE, BlazeEntityModel.method_31982());
		builder.put(EntityModelLayers.BOOK, BookModel.method_31986());
		builder.put(EntityModelLayers.CAT, lv10);
		builder.put(EntityModelLayers.CAT_COLLAR, class_5607.method_32110(OcelotEntityModel.method_32021(new class_5605(0.01F)), 64, 32));
		builder.put(EntityModelLayers.CAVE_SPIDER, lv18);
		builder.put(EntityModelLayers.CHEST, ChestBlockEntityRenderer.method_32147());
		builder.put(EntityModelLayers.DOUBLE_CHEST_LEFT, ChestBlockEntityRenderer.method_32149());
		builder.put(EntityModelLayers.DOUBLE_CHEST_RIGHT, ChestBlockEntityRenderer.method_32148());
		builder.put(EntityModelLayers.CHEST_MINECART, lv5);
		builder.put(EntityModelLayers.CHICKEN, ChickenEntityModel.method_31988());
		builder.put(EntityModelLayers.COD, CodEntityModel.method_31989());
		builder.put(EntityModelLayers.COMMAND_BLOCK_MINECART, lv5);
		builder.put(EntityModelLayers.CONDUIT_EYE, ConduitBlockEntityRenderer.method_32150());
		builder.put(EntityModelLayers.CONDUIT_WIND, ConduitBlockEntityRenderer.method_32151());
		builder.put(EntityModelLayers.CONDUIT_SHELL, ConduitBlockEntityRenderer.method_32152());
		builder.put(EntityModelLayers.CONDUIT, ConduitBlockEntityRenderer.method_32153());
		builder.put(EntityModelLayers.COW, lv9);
		builder.put(EntityModelLayers.CREEPER, CreeperEntityModel.method_31991(class_5605.field_27715));
		builder.put(EntityModelLayers.CREEPER_ARMOR, CreeperEntityModel.method_31991(new class_5605(2.0F)));
		builder.put(EntityModelLayers.CREEPER_HEAD, lv6);
		builder.put(EntityModelLayers.DOLPHIN, DolphinEntityModel.method_31992());
		builder.put(EntityModelLayers.DONKEY, DonkeyEntityModel.method_31987());
		builder.put(EntityModelLayers.DRAGON_SKULL, DragonHeadEntityModel.method_32071());
		builder.put(EntityModelLayers.DROWNED, DrownedEntityModel.method_31993(class_5605.field_27715));
		builder.put(EntityModelLayers.DROWNED_INNER_ARMOR, lv4);
		builder.put(EntityModelLayers.DROWNED_OUTER_ARMOR, lv4);
		builder.put(EntityModelLayers.DROWNED_OUTER, DrownedEntityModel.method_31993(new class_5605(0.25F)));
		builder.put(EntityModelLayers.ELDER_GUARDIAN, GuardianEntityModel.method_32002());
		builder.put(EntityModelLayers.ELYTRA, ElytraEntityModel.method_31994());
		builder.put(EntityModelLayers.ENDERMAN, EndermanEntityModel.method_31995());
		builder.put(EntityModelLayers.ENDERMITE, EndermiteEntityModel.method_31996());
		builder.put(EntityModelLayers.ENDER_DRAGON, EnderDragonEntityRenderer.method_32165());
		builder.put(EntityModelLayers.END_CRYSTAL, EndCrystalEntityRenderer.method_32164());
		builder.put(EntityModelLayers.EVOKER, lv8);
		builder.put(EntityModelLayers.EVOKER_FANGS, EvokerFangsEntityModel.method_31998());
		builder.put(EntityModelLayers.FOX, FoxEntityModel.method_31999());
		builder.put(EntityModelLayers.FURNACE_MINECART, lv5);
		builder.put(EntityModelLayers.GHAST, GhastEntityModel.method_32000());
		builder.put(EntityModelLayers.GIANT, lv);
		builder.put(EntityModelLayers.GIANT_INNER_ARMOR, lv4);
		builder.put(EntityModelLayers.GIANT_OUTER_ARMOR, lv2);
		builder.put(EntityModelLayers.GUARDIAN, GuardianEntityModel.method_32002());
		builder.put(EntityModelLayers.HOGLIN, lv15);
		builder.put(EntityModelLayers.HOPPER_MINECART, lv5);
		builder.put(EntityModelLayers.HORSE, lv7);
		builder.put(EntityModelLayers.HORSE_ARMOR, class_5607.method_32110(HorseEntityModel.method_32010(new class_5605(0.1F)), 64, 64));
		builder.put(EntityModelLayers.HUSK, lv);
		builder.put(EntityModelLayers.HUSK_INNER_ARMOR, lv4);
		builder.put(EntityModelLayers.HUSK_OUTER_ARMOR, lv2);
		builder.put(EntityModelLayers.ILLUSIONER, lv8);
		builder.put(EntityModelLayers.IRON_GOLEM, IronGolemEntityModel.method_32013());
		builder.put(EntityModelLayers.LEASH_KNOT, LeashKnotEntityModel.method_32017());
		builder.put(EntityModelLayers.LLAMA, lv13);
		builder.put(EntityModelLayers.LLAMA_DECOR, LlamaEntityModel.method_32018(new class_5605(0.5F)));
		builder.put(EntityModelLayers.LLAMA_SPIT, LlamaSpitEntityModel.method_32019());
		builder.put(EntityModelLayers.MAGMA_CUBE, MagmaCubeEntityModel.method_32014());
		builder.put(EntityModelLayers.MINECART, lv5);
		builder.put(EntityModelLayers.MOOSHROOM, lv9);
		builder.put(EntityModelLayers.MULE, DonkeyEntityModel.method_31987());
		builder.put(EntityModelLayers.OCELOT, lv10);
		builder.put(EntityModelLayers.PANDA, PandaEntityModel.method_32022());
		builder.put(EntityModelLayers.PARROT, ParrotEntityModel.method_32023());
		builder.put(EntityModelLayers.PHANTOM, PhantomEntityModel.method_32024());
		builder.put(EntityModelLayers.PIG, PigEntityModel.method_32025(class_5605.field_27715));
		builder.put(EntityModelLayers.PIG_SADDLE, PigEntityModel.method_32025(new class_5605(0.5F)));
		builder.put(EntityModelLayers.PIGLIN, lv11);
		builder.put(EntityModelLayers.PIGLIN_INNER_ARMOR, lv4);
		builder.put(EntityModelLayers.PIGLIN_OUTER_ARMOR, lv3);
		builder.put(EntityModelLayers.PIGLIN_BRUTE, lv11);
		builder.put(EntityModelLayers.PIGLIN_BRUTE_INNER_ARMOR, lv4);
		builder.put(EntityModelLayers.PIGLIN_BRUTE_OUTER_ARMOR, lv3);
		builder.put(EntityModelLayers.PILLAGER, lv8);
		builder.put(EntityModelLayers.PLAYER, class_5607.method_32110(PlayerEntityModel.method_32028(class_5605.field_27715, false), 64, 64));
		builder.put(EntityModelLayers.PLAYER_HEAD, lv12);
		builder.put(EntityModelLayers.PLAYER_INNER_ARMOR, lv4);
		builder.put(EntityModelLayers.PLAYER_OUTER_ARMOR, lv2);
		builder.put(EntityModelLayers.PLAYER_SLIM, class_5607.method_32110(PlayerEntityModel.method_32028(class_5605.field_27715, true), 64, 64));
		builder.put(EntityModelLayers.PLAYER_SLIM_INNER_ARMOR, lv4);
		builder.put(EntityModelLayers.PLAYER_SLIM_OUTER_ARMOR, lv2);
		builder.put(EntityModelLayers.SPIN_ATTACK, TridentRiptideFeatureRenderer.method_32200());
		builder.put(EntityModelLayers.POLAR_BEAR, PolarBearEntityModel.method_32029());
		builder.put(EntityModelLayers.PUFFERFISH_BIG, LargePufferfishEntityModel.method_32030());
		builder.put(EntityModelLayers.PUFFERFISH_MEDIUM, MediumPufferfishEntityModel.method_32031());
		builder.put(EntityModelLayers.PUFFERFISH_SMALL, SmallPufferfishEntityModel.method_32032());
		builder.put(EntityModelLayers.RABBIT, RabbitEntityModel.method_32034());
		builder.put(EntityModelLayers.RAVAGER, RavagerEntityModel.method_32035());
		builder.put(EntityModelLayers.SALMON, SalmonEntityModel.method_32036());
		builder.put(EntityModelLayers.SHEEP, SheepEntityModel.method_32038());
		builder.put(EntityModelLayers.SHEEP_FUR, SheepWoolEntityModel.method_32037());
		builder.put(EntityModelLayers.SHIELD, ShieldEntityModel.method_32039());
		builder.put(EntityModelLayers.SHULKER, ShulkerEntityModel.method_32041());
		builder.put(EntityModelLayers.SHULKER_BULLET, ShulkerBulletEntityModel.method_32040());
		builder.put(EntityModelLayers.SILVERFISH, SilverfishEntityModel.method_32042());
		builder.put(EntityModelLayers.SKELETON, lv16);
		builder.put(EntityModelLayers.SKELETON_INNER_ARMOR, lv4);
		builder.put(EntityModelLayers.SKELETON_OUTER_ARMOR, lv2);
		builder.put(EntityModelLayers.SKELETON_HORSE, lv7);
		builder.put(EntityModelLayers.SKELETON_SKULL, lv6);
		builder.put(EntityModelLayers.SLIME, SlimeEntityModel.method_32052());
		builder.put(EntityModelLayers.SLIME_OUTER, SlimeEntityModel.method_32051());
		builder.put(EntityModelLayers.SNOW_GOLEM, SnowGolemEntityModel.method_32053());
		builder.put(EntityModelLayers.SPAWNER_MINECART, lv5);
		builder.put(EntityModelLayers.SPIDER, lv18);
		builder.put(EntityModelLayers.SQUID, SquidEntityModel.method_32055());
		builder.put(EntityModelLayers.STRAY, lv16);
		builder.put(EntityModelLayers.STRAY_INNER_ARMOR, lv4);
		builder.put(EntityModelLayers.STRAY_OUTER_ARMOR, lv2);
		builder.put(EntityModelLayers.STRAY_OUTER, class_5607.method_32110(BipedEntityModel.method_32011(new class_5605(0.25F), 0.0F), 64, 32));
		builder.put(EntityModelLayers.STRIDER, lv14);
		builder.put(EntityModelLayers.STRIDER_SADDLE, lv14);
		builder.put(EntityModelLayers.TNT_MINECART, lv5);
		builder.put(EntityModelLayers.TRADER_LLAMA, lv13);
		builder.put(EntityModelLayers.TRIDENT, TridentEntityModel.method_32059());
		builder.put(EntityModelLayers.TROPICAL_FISH_LARGE, LargeTropicalFishEntityModel.method_32061(class_5605.field_27715));
		builder.put(EntityModelLayers.TROPICAL_FISH_LARGE_PATTERN, LargeTropicalFishEntityModel.method_32061(field_27543));
		builder.put(EntityModelLayers.TROPICAL_FISH_SMALL, SmallTropicalFishEntityModel.method_32060(class_5605.field_27715));
		builder.put(EntityModelLayers.TROPICAL_FISH_SMALL_PATTERN, SmallTropicalFishEntityModel.method_32060(field_27543));
		builder.put(EntityModelLayers.TURTLE, TurtleEntityModel.method_32062());
		builder.put(EntityModelLayers.VEX, VexEntityModel.method_32063());
		builder.put(EntityModelLayers.VILLAGER, lv17);
		builder.put(EntityModelLayers.VINDICATOR, lv8);
		builder.put(EntityModelLayers.WANDERING_TRADER, lv17);
		builder.put(EntityModelLayers.WITCH, WitchEntityModel.method_32065());
		builder.put(EntityModelLayers.WITHER, WitherEntityModel.method_32067(class_5605.field_27715));
		builder.put(EntityModelLayers.WITHER_ARMOR, WitherEntityModel.method_32067(field_27545));
		builder.put(EntityModelLayers.WITHER_SKULL, WitherSkullEntityRenderer.method_32199());
		builder.put(EntityModelLayers.WITHER_SKELETON, lv16);
		builder.put(EntityModelLayers.WITHER_SKELETON_INNER_ARMOR, lv4);
		builder.put(EntityModelLayers.WITHER_SKELETON_OUTER_ARMOR, lv2);
		builder.put(EntityModelLayers.WITHER_SKELETON_SKULL, lv6);
		builder.put(EntityModelLayers.WOLF, WolfEntityModel.method_32068());
		builder.put(EntityModelLayers.ZOGLIN, lv15);
		builder.put(EntityModelLayers.ZOMBIE, lv);
		builder.put(EntityModelLayers.ZOMBIE_INNER_ARMOR, lv4);
		builder.put(EntityModelLayers.ZOMBIE_OUTER_ARMOR, lv2);
		builder.put(EntityModelLayers.ZOMBIE_HEAD, lv12);
		builder.put(EntityModelLayers.ZOMBIE_HORSE, lv7);
		builder.put(EntityModelLayers.ZOMBIE_VILLAGER, ZombieVillagerEntityModel.method_32070());
		builder.put(EntityModelLayers.ZOMBIE_VILLAGER_INNER_ARMOR, ZombieVillagerEntityModel.method_32069(field_27545));
		builder.put(EntityModelLayers.ZOMBIE_VILLAGER_OUTER_ARMOR, ZombieVillagerEntityModel.method_32069(field_27544));
		builder.put(EntityModelLayers.ZOMBIFIED_PIGLIN, lv11);
		builder.put(EntityModelLayers.ZOMBIFIED_PIGLIN_INNER_ARMOR, lv4);
		builder.put(EntityModelLayers.ZOMBIFIED_PIGLIN_OUTER_ARMOR, lv3);
		class_5607 lv19 = BoatEntityModel.method_31985();

		for (BoatEntity.Type type : BoatEntity.Type.values()) {
			builder.put(EntityModelLayers.createBoat(type), lv19);
		}

		class_5607 lv20 = SignBlockEntityRenderer.method_32154();
		SignType.stream().forEach(signType -> builder.put(EntityModelLayers.createSign(signType), lv20));
		ImmutableMap<EntityModelLayer, class_5607> immutableMap = builder.build();
		List<EntityModelLayer> list = (List<EntityModelLayer>)EntityModelLayers.getLayers()
			.filter(entityModelLayer -> !immutableMap.containsKey(entityModelLayer))
			.collect(Collectors.toList());
		if (!list.isEmpty()) {
			throw new IllegalStateException("Missing layer definitions: " + list);
		} else {
			return Maps.transformValues(immutableMap, class_5607::method_32109);
		}
	}
}
