package net.minecraft.tag;

import net.minecraft.block.Block;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;

public final class BlockTags {
	public static final TagKey<Block> WOOL = register("wool");
	public static final TagKey<Block> PLANKS = register("planks");
	public static final TagKey<Block> STONE_BRICKS = register("stone_bricks");
	public static final TagKey<Block> WOODEN_BUTTONS = register("wooden_buttons");
	public static final TagKey<Block> BUTTONS = register("buttons");
	public static final TagKey<Block> CARPETS = register("carpets");
	public static final TagKey<Block> WOODEN_DOORS = register("wooden_doors");
	public static final TagKey<Block> WOODEN_STAIRS = register("wooden_stairs");
	public static final TagKey<Block> WOODEN_SLABS = register("wooden_slabs");
	public static final TagKey<Block> WOODEN_FENCES = register("wooden_fences");
	public static final TagKey<Block> PRESSURE_PLATES = register("pressure_plates");
	public static final TagKey<Block> WOODEN_PRESSURE_PLATES = register("wooden_pressure_plates");
	public static final TagKey<Block> STONE_PRESSURE_PLATES = register("stone_pressure_plates");
	public static final TagKey<Block> WOODEN_TRAPDOORS = register("wooden_trapdoors");
	public static final TagKey<Block> DOORS = register("doors");
	public static final TagKey<Block> SAPLINGS = register("saplings");
	public static final TagKey<Block> LOGS_THAT_BURN = register("logs_that_burn");
	public static final TagKey<Block> LOGS = register("logs");
	public static final TagKey<Block> DARK_OAK_LOGS = register("dark_oak_logs");
	public static final TagKey<Block> OAK_LOGS = register("oak_logs");
	public static final TagKey<Block> BIRCH_LOGS = register("birch_logs");
	public static final TagKey<Block> ACACIA_LOGS = register("acacia_logs");
	public static final TagKey<Block> JUNGLE_LOGS = register("jungle_logs");
	public static final TagKey<Block> SPRUCE_LOGS = register("spruce_logs");
	public static final TagKey<Block> CRIMSON_STEMS = register("crimson_stems");
	public static final TagKey<Block> WARPED_STEMS = register("warped_stems");
	public static final TagKey<Block> BANNERS = register("banners");
	public static final TagKey<Block> SAND = register("sand");
	public static final TagKey<Block> STAIRS = register("stairs");
	public static final TagKey<Block> SLABS = register("slabs");
	public static final TagKey<Block> WALLS = register("walls");
	public static final TagKey<Block> ANVIL = register("anvil");
	public static final TagKey<Block> RAILS = register("rails");
	public static final TagKey<Block> LEAVES = register("leaves");
	public static final TagKey<Block> TRAPDOORS = register("trapdoors");
	public static final TagKey<Block> SMALL_FLOWERS = register("small_flowers");
	public static final TagKey<Block> BEDS = register("beds");
	public static final TagKey<Block> FENCES = register("fences");
	public static final TagKey<Block> TALL_FLOWERS = register("tall_flowers");
	public static final TagKey<Block> FLOWERS = register("flowers");
	public static final TagKey<Block> PIGLIN_REPELLENTS = register("piglin_repellents");
	public static final TagKey<Block> GOLD_ORES = register("gold_ores");
	public static final TagKey<Block> IRON_ORES = register("iron_ores");
	public static final TagKey<Block> DIAMOND_ORES = register("diamond_ores");
	public static final TagKey<Block> REDSTONE_ORES = register("redstone_ores");
	public static final TagKey<Block> LAPIS_ORES = register("lapis_ores");
	public static final TagKey<Block> COAL_ORES = register("coal_ores");
	public static final TagKey<Block> EMERALD_ORES = register("emerald_ores");
	public static final TagKey<Block> COPPER_ORES = register("copper_ores");
	public static final TagKey<Block> NON_FLAMMABLE_WOOD = register("non_flammable_wood");
	public static final TagKey<Block> CANDLES = register("candles");
	public static final TagKey<Block> DIRT = register("dirt");
	public static final TagKey<Block> TERRACOTTA = register("terracotta");
	public static final TagKey<Block> FLOWER_POTS = register("flower_pots");
	public static final TagKey<Block> ENDERMAN_HOLDABLE = register("enderman_holdable");
	public static final TagKey<Block> ICE = register("ice");
	public static final TagKey<Block> VALID_SPAWN = register("valid_spawn");
	public static final TagKey<Block> IMPERMEABLE = register("impermeable");
	public static final TagKey<Block> UNDERWATER_BONEMEALS = register("underwater_bonemeals");
	public static final TagKey<Block> CORAL_BLOCKS = register("coral_blocks");
	public static final TagKey<Block> WALL_CORALS = register("wall_corals");
	public static final TagKey<Block> CORAL_PLANTS = register("coral_plants");
	public static final TagKey<Block> CORALS = register("corals");
	public static final TagKey<Block> BAMBOO_PLANTABLE_ON = register("bamboo_plantable_on");
	public static final TagKey<Block> STANDING_SIGNS = register("standing_signs");
	public static final TagKey<Block> WALL_SIGNS = register("wall_signs");
	public static final TagKey<Block> SIGNS = register("signs");
	public static final TagKey<Block> DRAGON_IMMUNE = register("dragon_immune");
	public static final TagKey<Block> WITHER_IMMUNE = register("wither_immune");
	public static final TagKey<Block> WITHER_SUMMON_BASE_BLOCKS = register("wither_summon_base_blocks");
	public static final TagKey<Block> BEEHIVES = register("beehives");
	public static final TagKey<Block> CROPS = register("crops");
	public static final TagKey<Block> BEE_GROWABLES = register("bee_growables");
	public static final TagKey<Block> PORTALS = register("portals");
	public static final TagKey<Block> FIRE = register("fire");
	public static final TagKey<Block> NYLIUM = register("nylium");
	public static final TagKey<Block> WART_BLOCKS = register("wart_blocks");
	public static final TagKey<Block> BEACON_BASE_BLOCKS = register("beacon_base_blocks");
	public static final TagKey<Block> SOUL_SPEED_BLOCKS = register("soul_speed_blocks");
	public static final TagKey<Block> WALL_POST_OVERRIDE = register("wall_post_override");
	public static final TagKey<Block> CLIMBABLE = register("climbable");
	public static final TagKey<Block> FALL_DAMAGE_RESETTING = register("fall_damage_resetting");
	public static final TagKey<Block> SHULKER_BOXES = register("shulker_boxes");
	public static final TagKey<Block> HOGLIN_REPELLENTS = register("hoglin_repellents");
	public static final TagKey<Block> SOUL_FIRE_BASE_BLOCKS = register("soul_fire_base_blocks");
	public static final TagKey<Block> STRIDER_WARM_BLOCKS = register("strider_warm_blocks");
	public static final TagKey<Block> CAMPFIRES = register("campfires");
	public static final TagKey<Block> GUARDED_BY_PIGLINS = register("guarded_by_piglins");
	public static final TagKey<Block> PREVENT_MOB_SPAWNING_INSIDE = register("prevent_mob_spawning_inside");
	public static final TagKey<Block> FENCE_GATES = register("fence_gates");
	public static final TagKey<Block> UNSTABLE_BOTTOM_CENTER = register("unstable_bottom_center");
	public static final TagKey<Block> MUSHROOM_GROW_BLOCK = register("mushroom_grow_block");
	public static final TagKey<Block> INFINIBURN_OVERWORLD = register("infiniburn_overworld");
	public static final TagKey<Block> INFINIBURN_NETHER = register("infiniburn_nether");
	public static final TagKey<Block> INFINIBURN_END = register("infiniburn_end");
	public static final TagKey<Block> BASE_STONE_OVERWORLD = register("base_stone_overworld");
	public static final TagKey<Block> STONE_ORE_REPLACEABLES = register("stone_ore_replaceables");
	public static final TagKey<Block> DEEPSLATE_ORE_REPLACEABLES = register("deepslate_ore_replaceables");
	public static final TagKey<Block> BASE_STONE_NETHER = register("base_stone_nether");
	public static final TagKey<Block> CANDLE_CAKES = register("candle_cakes");
	public static final TagKey<Block> CAULDRONS = register("cauldrons");
	public static final TagKey<Block> CRYSTAL_SOUND_BLOCKS = register("crystal_sound_blocks");
	public static final TagKey<Block> INSIDE_STEP_SOUND_BLOCKS = register("inside_step_sound_blocks");
	public static final TagKey<Block> OCCLUDES_VIBRATION_SIGNALS = register("occludes_vibration_signals");
	public static final TagKey<Block> DRIPSTONE_REPLACEABLE_BLOCKS = register("dripstone_replaceable_blocks");
	public static final TagKey<Block> CAVE_VINES = register("cave_vines");
	public static final TagKey<Block> MOSS_REPLACEABLE = register("moss_replaceable");
	public static final TagKey<Block> LUSH_GROUND_REPLACEABLE = register("lush_ground_replaceable");
	public static final TagKey<Block> AZALEA_ROOT_REPLACEABLE = register("azalea_root_replaceable");
	public static final TagKey<Block> SMALL_DRIPLEAF_PLACEABLE = register("small_dripleaf_placeable");
	public static final TagKey<Block> BIG_DRIPLEAF_PLACEABLE = register("big_dripleaf_placeable");
	public static final TagKey<Block> SNOW = register("snow");
	public static final TagKey<Block> FRAGILE = register("fragile");
	public static final TagKey<Block> AXE_MINEABLE = register("mineable/axe");
	public static final TagKey<Block> HOE_MINEABLE = register("mineable/hoe");
	public static final TagKey<Block> PICKAXE_MINEABLE = register("mineable/pickaxe");
	public static final TagKey<Block> SHOVEL_MINEABLE = register("mineable/shovel");
	public static final TagKey<Block> NEEDS_DIAMOND_TOOL = register("needs_diamond_tool");
	public static final TagKey<Block> NEEDS_IRON_TOOL = register("needs_iron_tool");
	public static final TagKey<Block> NEEDS_STONE_TOOL = register("needs_stone_tool");
	public static final TagKey<Block> FEATURES_CANNOT_REPLACE = register("features_cannot_replace");
	public static final TagKey<Block> LAVA_POOL_STONE_CANNOT_REPLACE = register("lava_pool_stone_cannot_replace");
	public static final TagKey<Block> GEODE_INVALID_BLOCKS = register("geode_invalid_blocks");
	public static final TagKey<Block> SCULK_REPLACEABLE = register("sculk_replaceable");
	public static final TagKey<Block> ANIMALS_SPAWNABLE_ON = register("animals_spawnable_on");
	public static final TagKey<Block> AXOLOTLS_SPAWNABLE_ON = register("axolotls_spawnable_on");
	public static final TagKey<Block> GOATS_SPAWNABLE_ON = register("goats_spawnable_on");
	public static final TagKey<Block> MOOSHROOMS_SPAWNABLE_ON = register("mooshrooms_spawnable_on");
	public static final TagKey<Block> PARROTS_SPAWNABLE_ON = register("parrots_spawnable_on");
	public static final TagKey<Block> POLAR_BEARS_SPAWNABLE_ON_IN_FROZEN_OCEAN = register("polar_bears_spawnable_on_in_frozen_ocean");
	public static final TagKey<Block> RABBITS_SPAWNABLE_ON = register("rabbits_spawnable_on");
	public static final TagKey<Block> FOXES_SPAWNABLE_ON = register("foxes_spawnable_on");
	public static final TagKey<Block> WOLVES_SPAWNABLE_ON = register("wolves_spawnable_on");
	public static final TagKey<Block> AZALEA_GROWS_ON = register("azalea_grows_on");
	public static final TagKey<Block> REPLACEABLE_PLANTS = register("replaceable_plants");

	private BlockTags() {
	}

	private static TagKey<Block> register(String id) {
		return TagKey.of(Registry.BLOCK_KEY, new Identifier(id));
	}
}
