package net.minecraft.world.biome;

import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;
import net.minecraft.util.registry.RegistryKey;

public abstract class Biomes {
	public static final RegistryKey<Biome> field_9423 = register("ocean");
	public static final RegistryKey<Biome> field_9451 = register("plains");
	public static final RegistryKey<Biome> field_9424 = register("desert");
	public static final RegistryKey<Biome> field_9472 = register("mountains");
	public static final RegistryKey<Biome> field_9409 = register("forest");
	public static final RegistryKey<Biome> field_9420 = register("taiga");
	public static final RegistryKey<Biome> field_9471 = register("swamp");
	public static final RegistryKey<Biome> field_9438 = register("river");
	public static final RegistryKey<Biome> field_9461 = register("nether_wastes");
	public static final RegistryKey<Biome> field_9411 = register("the_end");
	public static final RegistryKey<Biome> field_9435 = register("frozen_ocean");
	public static final RegistryKey<Biome> field_9463 = register("frozen_river");
	public static final RegistryKey<Biome> field_9452 = register("snowy_tundra");
	public static final RegistryKey<Biome> field_9444 = register("snowy_mountains");
	public static final RegistryKey<Biome> field_9462 = register("mushroom_fields");
	public static final RegistryKey<Biome> field_9407 = register("mushroom_field_shore");
	public static final RegistryKey<Biome> field_9434 = register("beach");
	public static final RegistryKey<Biome> field_9466 = register("desert_hills");
	public static final RegistryKey<Biome> field_9459 = register("wooded_hills");
	public static final RegistryKey<Biome> field_9428 = register("taiga_hills");
	public static final RegistryKey<Biome> field_9464 = register("mountain_edge");
	public static final RegistryKey<Biome> field_9417 = register("jungle");
	public static final RegistryKey<Biome> field_9432 = register("jungle_hills");
	public static final RegistryKey<Biome> field_9474 = register("jungle_edge");
	public static final RegistryKey<Biome> field_9446 = register("deep_ocean");
	public static final RegistryKey<Biome> field_9419 = register("stone_shore");
	public static final RegistryKey<Biome> field_9478 = register("snowy_beach");
	public static final RegistryKey<Biome> field_9412 = register("birch_forest");
	public static final RegistryKey<Biome> field_9421 = register("birch_forest_hills");
	public static final RegistryKey<Biome> field_9475 = register("dark_forest");
	public static final RegistryKey<Biome> field_9454 = register("snowy_taiga");
	public static final RegistryKey<Biome> field_9425 = register("snowy_taiga_hills");
	public static final RegistryKey<Biome> field_9477 = register("giant_tree_taiga");
	public static final RegistryKey<Biome> field_9429 = register("giant_tree_taiga_hills");
	public static final RegistryKey<Biome> field_9460 = register("wooded_mountains");
	public static final RegistryKey<Biome> field_9449 = register("savanna");
	public static final RegistryKey<Biome> field_9430 = register("savanna_plateau");
	public static final RegistryKey<Biome> field_9415 = register("badlands");
	public static final RegistryKey<Biome> field_9410 = register("wooded_badlands_plateau");
	public static final RegistryKey<Biome> field_9433 = register("badlands_plateau");
	public static final RegistryKey<Biome> field_9457 = register("small_end_islands");
	public static final RegistryKey<Biome> field_9447 = register("end_midlands");
	public static final RegistryKey<Biome> field_9442 = register("end_highlands");
	public static final RegistryKey<Biome> field_9465 = register("end_barrens");
	public static final RegistryKey<Biome> field_9408 = register("warm_ocean");
	public static final RegistryKey<Biome> field_9441 = register("lukewarm_ocean");
	public static final RegistryKey<Biome> field_9467 = register("cold_ocean");
	public static final RegistryKey<Biome> field_9448 = register("deep_warm_ocean");
	public static final RegistryKey<Biome> field_9439 = register("deep_lukewarm_ocean");
	public static final RegistryKey<Biome> field_9470 = register("deep_cold_ocean");
	public static final RegistryKey<Biome> field_9418 = register("deep_frozen_ocean");
	public static final RegistryKey<Biome> field_9473 = register("the_void");
	public static final RegistryKey<Biome> field_9455 = register("sunflower_plains");
	public static final RegistryKey<Biome> field_9427 = register("desert_lakes");
	public static final RegistryKey<Biome> field_9476 = register("gravelly_mountains");
	public static final RegistryKey<Biome> field_9414 = register("flower_forest");
	public static final RegistryKey<Biome> field_9422 = register("taiga_mountains");
	public static final RegistryKey<Biome> field_9479 = register("swamp_hills");
	public static final RegistryKey<Biome> field_9453 = register("ice_spikes");
	public static final RegistryKey<Biome> field_9426 = register("modified_jungle");
	public static final RegistryKey<Biome> field_9405 = register("modified_jungle_edge");
	public static final RegistryKey<Biome> field_9431 = register("tall_birch_forest");
	public static final RegistryKey<Biome> field_9458 = register("tall_birch_hills");
	public static final RegistryKey<Biome> field_9450 = register("dark_forest_hills");
	public static final RegistryKey<Biome> field_9437 = register("snowy_taiga_mountains");
	public static final RegistryKey<Biome> field_9416 = register("giant_spruce_taiga");
	public static final RegistryKey<Biome> field_9404 = register("giant_spruce_taiga_hills");
	public static final RegistryKey<Biome> field_9436 = register("modified_gravelly_mountains");
	public static final RegistryKey<Biome> field_9456 = register("shattered_savanna");
	public static final RegistryKey<Biome> field_9445 = register("shattered_savanna_plateau");
	public static final RegistryKey<Biome> field_9443 = register("eroded_badlands");
	public static final RegistryKey<Biome> field_9413 = register("modified_wooded_badlands_plateau");
	public static final RegistryKey<Biome> field_9406 = register("modified_badlands_plateau");
	public static final RegistryKey<Biome> field_9440 = register("bamboo_jungle");
	public static final RegistryKey<Biome> field_9468 = register("bamboo_jungle_hills");
	public static final RegistryKey<Biome> field_22076 = register("soul_sand_valley");
	public static final RegistryKey<Biome> field_22077 = register("crimson_forest");
	public static final RegistryKey<Biome> field_22075 = register("warped_forest");
	public static final RegistryKey<Biome> field_23859 = register("basalt_deltas");

	private static RegistryKey<Biome> register(String string) {
		return RegistryKey.of(Registry.BIOME_KEY, new Identifier(string));
	}
}
