/*
 * Decompiled with CFR 0.2.0 (FabricMC d28b102d).
 */
package net.minecraft.tag;

import net.minecraft.block.Block;
import net.minecraft.tag.TagKey;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;

public final class BlockTags {
    public static final TagKey<Block> WOOL = BlockTags.of("wool");
    public static final TagKey<Block> PLANKS = BlockTags.of("planks");
    public static final TagKey<Block> STONE_BRICKS = BlockTags.of("stone_bricks");
    public static final TagKey<Block> WOODEN_BUTTONS = BlockTags.of("wooden_buttons");
    public static final TagKey<Block> BUTTONS = BlockTags.of("buttons");
    public static final TagKey<Block> WOOL_CARPETS = BlockTags.of("wool_carpets");
    public static final TagKey<Block> WOODEN_DOORS = BlockTags.of("wooden_doors");
    public static final TagKey<Block> WOODEN_STAIRS = BlockTags.of("wooden_stairs");
    public static final TagKey<Block> WOODEN_SLABS = BlockTags.of("wooden_slabs");
    public static final TagKey<Block> WOODEN_FENCES = BlockTags.of("wooden_fences");
    public static final TagKey<Block> PRESSURE_PLATES = BlockTags.of("pressure_plates");
    public static final TagKey<Block> WOODEN_PRESSURE_PLATES = BlockTags.of("wooden_pressure_plates");
    public static final TagKey<Block> STONE_PRESSURE_PLATES = BlockTags.of("stone_pressure_plates");
    public static final TagKey<Block> WOODEN_TRAPDOORS = BlockTags.of("wooden_trapdoors");
    public static final TagKey<Block> DOORS = BlockTags.of("doors");
    public static final TagKey<Block> SAPLINGS = BlockTags.of("saplings");
    public static final TagKey<Block> LOGS_THAT_BURN = BlockTags.of("logs_that_burn");
    public static final TagKey<Block> LOGS = BlockTags.of("logs");
    public static final TagKey<Block> DARK_OAK_LOGS = BlockTags.of("dark_oak_logs");
    public static final TagKey<Block> OAK_LOGS = BlockTags.of("oak_logs");
    public static final TagKey<Block> BIRCH_LOGS = BlockTags.of("birch_logs");
    public static final TagKey<Block> ACACIA_LOGS = BlockTags.of("acacia_logs");
    public static final TagKey<Block> JUNGLE_LOGS = BlockTags.of("jungle_logs");
    public static final TagKey<Block> SPRUCE_LOGS = BlockTags.of("spruce_logs");
    public static final TagKey<Block> MANGROVE_LOGS = BlockTags.of("mangrove_logs");
    public static final TagKey<Block> CRIMSON_STEMS = BlockTags.of("crimson_stems");
    public static final TagKey<Block> WARPED_STEMS = BlockTags.of("warped_stems");
    public static final TagKey<Block> BANNERS = BlockTags.of("banners");
    public static final TagKey<Block> SAND = BlockTags.of("sand");
    public static final TagKey<Block> STAIRS = BlockTags.of("stairs");
    public static final TagKey<Block> SLABS = BlockTags.of("slabs");
    public static final TagKey<Block> WALLS = BlockTags.of("walls");
    public static final TagKey<Block> ANVIL = BlockTags.of("anvil");
    public static final TagKey<Block> RAILS = BlockTags.of("rails");
    public static final TagKey<Block> LEAVES = BlockTags.of("leaves");
    public static final TagKey<Block> TRAPDOORS = BlockTags.of("trapdoors");
    public static final TagKey<Block> SMALL_FLOWERS = BlockTags.of("small_flowers");
    public static final TagKey<Block> BEDS = BlockTags.of("beds");
    public static final TagKey<Block> FENCES = BlockTags.of("fences");
    public static final TagKey<Block> TALL_FLOWERS = BlockTags.of("tall_flowers");
    public static final TagKey<Block> FLOWERS = BlockTags.of("flowers");
    public static final TagKey<Block> PIGLIN_REPELLENTS = BlockTags.of("piglin_repellents");
    public static final TagKey<Block> GOLD_ORES = BlockTags.of("gold_ores");
    public static final TagKey<Block> IRON_ORES = BlockTags.of("iron_ores");
    public static final TagKey<Block> DIAMOND_ORES = BlockTags.of("diamond_ores");
    public static final TagKey<Block> REDSTONE_ORES = BlockTags.of("redstone_ores");
    public static final TagKey<Block> LAPIS_ORES = BlockTags.of("lapis_ores");
    public static final TagKey<Block> COAL_ORES = BlockTags.of("coal_ores");
    public static final TagKey<Block> EMERALD_ORES = BlockTags.of("emerald_ores");
    public static final TagKey<Block> COPPER_ORES = BlockTags.of("copper_ores");
    public static final TagKey<Block> NON_FLAMMABLE_WOOD = BlockTags.of("non_flammable_wood");
    public static final TagKey<Block> CANDLES = BlockTags.of("candles");
    public static final TagKey<Block> DIRT = BlockTags.of("dirt");
    public static final TagKey<Block> TERRACOTTA = BlockTags.of("terracotta");
    public static final TagKey<Block> FLOWER_POTS = BlockTags.of("flower_pots");
    public static final TagKey<Block> ENDERMAN_HOLDABLE = BlockTags.of("enderman_holdable");
    public static final TagKey<Block> ICE = BlockTags.of("ice");
    public static final TagKey<Block> VALID_SPAWN = BlockTags.of("valid_spawn");
    public static final TagKey<Block> IMPERMEABLE = BlockTags.of("impermeable");
    public static final TagKey<Block> UNDERWATER_BONEMEALS = BlockTags.of("underwater_bonemeals");
    public static final TagKey<Block> CORAL_BLOCKS = BlockTags.of("coral_blocks");
    public static final TagKey<Block> WALL_CORALS = BlockTags.of("wall_corals");
    public static final TagKey<Block> CORAL_PLANTS = BlockTags.of("coral_plants");
    public static final TagKey<Block> CORALS = BlockTags.of("corals");
    public static final TagKey<Block> BAMBOO_PLANTABLE_ON = BlockTags.of("bamboo_plantable_on");
    public static final TagKey<Block> STANDING_SIGNS = BlockTags.of("standing_signs");
    public static final TagKey<Block> WALL_SIGNS = BlockTags.of("wall_signs");
    public static final TagKey<Block> SIGNS = BlockTags.of("signs");
    public static final TagKey<Block> DRAGON_IMMUNE = BlockTags.of("dragon_immune");
    public static final TagKey<Block> DRAGON_TRANSPARENT = BlockTags.of("dragon_transparent");
    public static final TagKey<Block> WITHER_IMMUNE = BlockTags.of("wither_immune");
    public static final TagKey<Block> WITHER_SUMMON_BASE_BLOCKS = BlockTags.of("wither_summon_base_blocks");
    public static final TagKey<Block> BEEHIVES = BlockTags.of("beehives");
    public static final TagKey<Block> CROPS = BlockTags.of("crops");
    public static final TagKey<Block> BEE_GROWABLES = BlockTags.of("bee_growables");
    public static final TagKey<Block> PORTALS = BlockTags.of("portals");
    public static final TagKey<Block> FIRE = BlockTags.of("fire");
    public static final TagKey<Block> NYLIUM = BlockTags.of("nylium");
    public static final TagKey<Block> WART_BLOCKS = BlockTags.of("wart_blocks");
    public static final TagKey<Block> BEACON_BASE_BLOCKS = BlockTags.of("beacon_base_blocks");
    public static final TagKey<Block> SOUL_SPEED_BLOCKS = BlockTags.of("soul_speed_blocks");
    public static final TagKey<Block> WALL_POST_OVERRIDE = BlockTags.of("wall_post_override");
    public static final TagKey<Block> CLIMBABLE = BlockTags.of("climbable");
    public static final TagKey<Block> FALL_DAMAGE_RESETTING = BlockTags.of("fall_damage_resetting");
    public static final TagKey<Block> SHULKER_BOXES = BlockTags.of("shulker_boxes");
    public static final TagKey<Block> HOGLIN_REPELLENTS = BlockTags.of("hoglin_repellents");
    public static final TagKey<Block> SOUL_FIRE_BASE_BLOCKS = BlockTags.of("soul_fire_base_blocks");
    public static final TagKey<Block> STRIDER_WARM_BLOCKS = BlockTags.of("strider_warm_blocks");
    public static final TagKey<Block> CAMPFIRES = BlockTags.of("campfires");
    public static final TagKey<Block> GUARDED_BY_PIGLINS = BlockTags.of("guarded_by_piglins");
    public static final TagKey<Block> PREVENT_MOB_SPAWNING_INSIDE = BlockTags.of("prevent_mob_spawning_inside");
    public static final TagKey<Block> FENCE_GATES = BlockTags.of("fence_gates");
    public static final TagKey<Block> UNSTABLE_BOTTOM_CENTER = BlockTags.of("unstable_bottom_center");
    public static final TagKey<Block> MUSHROOM_GROW_BLOCK = BlockTags.of("mushroom_grow_block");
    public static final TagKey<Block> INFINIBURN_OVERWORLD = BlockTags.of("infiniburn_overworld");
    public static final TagKey<Block> INFINIBURN_NETHER = BlockTags.of("infiniburn_nether");
    public static final TagKey<Block> INFINIBURN_END = BlockTags.of("infiniburn_end");
    public static final TagKey<Block> BASE_STONE_OVERWORLD = BlockTags.of("base_stone_overworld");
    public static final TagKey<Block> STONE_ORE_REPLACEABLES = BlockTags.of("stone_ore_replaceables");
    public static final TagKey<Block> DEEPSLATE_ORE_REPLACEABLES = BlockTags.of("deepslate_ore_replaceables");
    public static final TagKey<Block> BASE_STONE_NETHER = BlockTags.of("base_stone_nether");
    public static final TagKey<Block> CANDLE_CAKES = BlockTags.of("candle_cakes");
    public static final TagKey<Block> CAULDRONS = BlockTags.of("cauldrons");
    public static final TagKey<Block> CRYSTAL_SOUND_BLOCKS = BlockTags.of("crystal_sound_blocks");
    public static final TagKey<Block> INSIDE_STEP_SOUND_BLOCKS = BlockTags.of("inside_step_sound_blocks");
    public static final TagKey<Block> OCCLUDES_VIBRATION_SIGNALS = BlockTags.of("occludes_vibration_signals");
    public static final TagKey<Block> DRIPSTONE_REPLACEABLE_BLOCKS = BlockTags.of("dripstone_replaceable_blocks");
    public static final TagKey<Block> CAVE_VINES = BlockTags.of("cave_vines");
    public static final TagKey<Block> MOSS_REPLACEABLE = BlockTags.of("moss_replaceable");
    public static final TagKey<Block> LUSH_GROUND_REPLACEABLE = BlockTags.of("lush_ground_replaceable");
    public static final TagKey<Block> AZALEA_ROOT_REPLACEABLE = BlockTags.of("azalea_root_replaceable");
    public static final TagKey<Block> SMALL_DRIPLEAF_PLACEABLE = BlockTags.of("small_dripleaf_placeable");
    public static final TagKey<Block> BIG_DRIPLEAF_PLACEABLE = BlockTags.of("big_dripleaf_placeable");
    public static final TagKey<Block> SNOW = BlockTags.of("snow");
    public static final TagKey<Block> AXE_MINEABLE = BlockTags.of("mineable/axe");
    public static final TagKey<Block> HOE_MINEABLE = BlockTags.of("mineable/hoe");
    public static final TagKey<Block> PICKAXE_MINEABLE = BlockTags.of("mineable/pickaxe");
    public static final TagKey<Block> SHOVEL_MINEABLE = BlockTags.of("mineable/shovel");
    public static final TagKey<Block> NEEDS_DIAMOND_TOOL = BlockTags.of("needs_diamond_tool");
    public static final TagKey<Block> NEEDS_IRON_TOOL = BlockTags.of("needs_iron_tool");
    public static final TagKey<Block> NEEDS_STONE_TOOL = BlockTags.of("needs_stone_tool");
    public static final TagKey<Block> FEATURES_CANNOT_REPLACE = BlockTags.of("features_cannot_replace");
    public static final TagKey<Block> LAVA_POOL_STONE_CANNOT_REPLACE = BlockTags.of("lava_pool_stone_cannot_replace");
    public static final TagKey<Block> GEODE_INVALID_BLOCKS = BlockTags.of("geode_invalid_blocks");
    public static final TagKey<Block> FROG_PREFER_JUMP_TO = BlockTags.of("frog_prefer_jump_to");
    public static final TagKey<Block> SCULK_REPLACEABLE = BlockTags.of("sculk_replaceable");
    public static final TagKey<Block> SCULK_REPLACEABLE_WORLD_GEN = BlockTags.of("sculk_replaceable_world_gen");
    public static final TagKey<Block> ANCIENT_CITY_REPLACEABLE = BlockTags.of("ancient_city_replaceable");
    public static final TagKey<Block> ANIMALS_SPAWNABLE_ON = BlockTags.of("animals_spawnable_on");
    public static final TagKey<Block> AXOLOTLS_SPAWNABLE_ON = BlockTags.of("axolotls_spawnable_on");
    public static final TagKey<Block> GOATS_SPAWNABLE_ON = BlockTags.of("goats_spawnable_on");
    public static final TagKey<Block> MOOSHROOMS_SPAWNABLE_ON = BlockTags.of("mooshrooms_spawnable_on");
    public static final TagKey<Block> PARROTS_SPAWNABLE_ON = BlockTags.of("parrots_spawnable_on");
    public static final TagKey<Block> POLAR_BEARS_SPAWNABLE_ON_ALTERNATE = BlockTags.of("polar_bears_spawnable_on_alternate");
    public static final TagKey<Block> RABBITS_SPAWNABLE_ON = BlockTags.of("rabbits_spawnable_on");
    public static final TagKey<Block> FOXES_SPAWNABLE_ON = BlockTags.of("foxes_spawnable_on");
    public static final TagKey<Block> WOLVES_SPAWNABLE_ON = BlockTags.of("wolves_spawnable_on");
    public static final TagKey<Block> AZALEA_GROWS_ON = BlockTags.of("azalea_grows_on");
    public static final TagKey<Block> REPLACEABLE_PLANTS = BlockTags.of("replaceable_plants");
    public static final TagKey<Block> CONVERTABLE_TO_MUD = BlockTags.of("convertable_to_mud");
    public static final TagKey<Block> MANGROVE_LOGS_CAN_GROW_THROUGH = BlockTags.of("mangrove_logs_can_grow_through");
    public static final TagKey<Block> MANGROVE_ROOTS_CAN_GROW_THROUGH = BlockTags.of("mangrove_roots_can_grow_through");
    public static final TagKey<Block> DEAD_BUSH_MAY_PLACE_ON = BlockTags.of("dead_bush_may_place_on");

    private BlockTags() {
    }

    private static TagKey<Block> of(String id) {
        return TagKey.of(Registry.BLOCK_KEY, new Identifier(id));
    }
}

