/*
 * Decompiled with CFR 0.2.0 (FabricMC d28b102d).
 */
package net.minecraft.tag;

import net.minecraft.block.Block;
import net.minecraft.tag.TagKey;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;

public final class BlockTags {
    public static final TagKey<Block> WOOL = BlockTags.register("wool");
    public static final TagKey<Block> PLANKS = BlockTags.register("planks");
    public static final TagKey<Block> STONE_BRICKS = BlockTags.register("stone_bricks");
    public static final TagKey<Block> WOODEN_BUTTONS = BlockTags.register("wooden_buttons");
    public static final TagKey<Block> BUTTONS = BlockTags.register("buttons");
    public static final TagKey<Block> CARPETS = BlockTags.register("carpets");
    public static final TagKey<Block> WOODEN_DOORS = BlockTags.register("wooden_doors");
    public static final TagKey<Block> WOODEN_STAIRS = BlockTags.register("wooden_stairs");
    public static final TagKey<Block> WOODEN_SLABS = BlockTags.register("wooden_slabs");
    public static final TagKey<Block> WOODEN_FENCES = BlockTags.register("wooden_fences");
    public static final TagKey<Block> PRESSURE_PLATES = BlockTags.register("pressure_plates");
    public static final TagKey<Block> WOODEN_PRESSURE_PLATES = BlockTags.register("wooden_pressure_plates");
    public static final TagKey<Block> STONE_PRESSURE_PLATES = BlockTags.register("stone_pressure_plates");
    public static final TagKey<Block> WOODEN_TRAPDOORS = BlockTags.register("wooden_trapdoors");
    public static final TagKey<Block> DOORS = BlockTags.register("doors");
    public static final TagKey<Block> SAPLINGS = BlockTags.register("saplings");
    public static final TagKey<Block> LOGS_THAT_BURN = BlockTags.register("logs_that_burn");
    public static final TagKey<Block> LOGS = BlockTags.register("logs");
    public static final TagKey<Block> DARK_OAK_LOGS = BlockTags.register("dark_oak_logs");
    public static final TagKey<Block> OAK_LOGS = BlockTags.register("oak_logs");
    public static final TagKey<Block> BIRCH_LOGS = BlockTags.register("birch_logs");
    public static final TagKey<Block> ACACIA_LOGS = BlockTags.register("acacia_logs");
    public static final TagKey<Block> JUNGLE_LOGS = BlockTags.register("jungle_logs");
    public static final TagKey<Block> SPRUCE_LOGS = BlockTags.register("spruce_logs");
    public static final TagKey<Block> CRIMSON_STEMS = BlockTags.register("crimson_stems");
    public static final TagKey<Block> WARPED_STEMS = BlockTags.register("warped_stems");
    public static final TagKey<Block> BANNERS = BlockTags.register("banners");
    public static final TagKey<Block> SAND = BlockTags.register("sand");
    public static final TagKey<Block> STAIRS = BlockTags.register("stairs");
    public static final TagKey<Block> SLABS = BlockTags.register("slabs");
    public static final TagKey<Block> WALLS = BlockTags.register("walls");
    public static final TagKey<Block> ANVIL = BlockTags.register("anvil");
    public static final TagKey<Block> RAILS = BlockTags.register("rails");
    public static final TagKey<Block> LEAVES = BlockTags.register("leaves");
    public static final TagKey<Block> TRAPDOORS = BlockTags.register("trapdoors");
    public static final TagKey<Block> SMALL_FLOWERS = BlockTags.register("small_flowers");
    public static final TagKey<Block> BEDS = BlockTags.register("beds");
    public static final TagKey<Block> FENCES = BlockTags.register("fences");
    public static final TagKey<Block> TALL_FLOWERS = BlockTags.register("tall_flowers");
    public static final TagKey<Block> FLOWERS = BlockTags.register("flowers");
    public static final TagKey<Block> PIGLIN_REPELLENTS = BlockTags.register("piglin_repellents");
    public static final TagKey<Block> GOLD_ORES = BlockTags.register("gold_ores");
    public static final TagKey<Block> IRON_ORES = BlockTags.register("iron_ores");
    public static final TagKey<Block> DIAMOND_ORES = BlockTags.register("diamond_ores");
    public static final TagKey<Block> REDSTONE_ORES = BlockTags.register("redstone_ores");
    public static final TagKey<Block> LAPIS_ORES = BlockTags.register("lapis_ores");
    public static final TagKey<Block> COAL_ORES = BlockTags.register("coal_ores");
    public static final TagKey<Block> EMERALD_ORES = BlockTags.register("emerald_ores");
    public static final TagKey<Block> COPPER_ORES = BlockTags.register("copper_ores");
    public static final TagKey<Block> NON_FLAMMABLE_WOOD = BlockTags.register("non_flammable_wood");
    public static final TagKey<Block> CANDLES = BlockTags.register("candles");
    public static final TagKey<Block> DIRT = BlockTags.register("dirt");
    public static final TagKey<Block> TERRACOTTA = BlockTags.register("terracotta");
    public static final TagKey<Block> FLOWER_POTS = BlockTags.register("flower_pots");
    public static final TagKey<Block> ENDERMAN_HOLDABLE = BlockTags.register("enderman_holdable");
    public static final TagKey<Block> ICE = BlockTags.register("ice");
    public static final TagKey<Block> VALID_SPAWN = BlockTags.register("valid_spawn");
    public static final TagKey<Block> IMPERMEABLE = BlockTags.register("impermeable");
    public static final TagKey<Block> UNDERWATER_BONEMEALS = BlockTags.register("underwater_bonemeals");
    public static final TagKey<Block> CORAL_BLOCKS = BlockTags.register("coral_blocks");
    public static final TagKey<Block> WALL_CORALS = BlockTags.register("wall_corals");
    public static final TagKey<Block> CORAL_PLANTS = BlockTags.register("coral_plants");
    public static final TagKey<Block> CORALS = BlockTags.register("corals");
    public static final TagKey<Block> BAMBOO_PLANTABLE_ON = BlockTags.register("bamboo_plantable_on");
    public static final TagKey<Block> STANDING_SIGNS = BlockTags.register("standing_signs");
    public static final TagKey<Block> WALL_SIGNS = BlockTags.register("wall_signs");
    public static final TagKey<Block> SIGNS = BlockTags.register("signs");
    public static final TagKey<Block> DRAGON_IMMUNE = BlockTags.register("dragon_immune");
    public static final TagKey<Block> WITHER_IMMUNE = BlockTags.register("wither_immune");
    public static final TagKey<Block> WITHER_SUMMON_BASE_BLOCKS = BlockTags.register("wither_summon_base_blocks");
    public static final TagKey<Block> BEEHIVES = BlockTags.register("beehives");
    public static final TagKey<Block> CROPS = BlockTags.register("crops");
    public static final TagKey<Block> BEE_GROWABLES = BlockTags.register("bee_growables");
    public static final TagKey<Block> PORTALS = BlockTags.register("portals");
    public static final TagKey<Block> FIRE = BlockTags.register("fire");
    public static final TagKey<Block> NYLIUM = BlockTags.register("nylium");
    public static final TagKey<Block> WART_BLOCKS = BlockTags.register("wart_blocks");
    public static final TagKey<Block> BEACON_BASE_BLOCKS = BlockTags.register("beacon_base_blocks");
    public static final TagKey<Block> SOUL_SPEED_BLOCKS = BlockTags.register("soul_speed_blocks");
    public static final TagKey<Block> WALL_POST_OVERRIDE = BlockTags.register("wall_post_override");
    public static final TagKey<Block> CLIMBABLE = BlockTags.register("climbable");
    public static final TagKey<Block> FALL_DAMAGE_RESETTING = BlockTags.register("fall_damage_resetting");
    public static final TagKey<Block> SHULKER_BOXES = BlockTags.register("shulker_boxes");
    public static final TagKey<Block> HOGLIN_REPELLENTS = BlockTags.register("hoglin_repellents");
    public static final TagKey<Block> SOUL_FIRE_BASE_BLOCKS = BlockTags.register("soul_fire_base_blocks");
    public static final TagKey<Block> STRIDER_WARM_BLOCKS = BlockTags.register("strider_warm_blocks");
    public static final TagKey<Block> CAMPFIRES = BlockTags.register("campfires");
    public static final TagKey<Block> GUARDED_BY_PIGLINS = BlockTags.register("guarded_by_piglins");
    public static final TagKey<Block> PREVENT_MOB_SPAWNING_INSIDE = BlockTags.register("prevent_mob_spawning_inside");
    public static final TagKey<Block> FENCE_GATES = BlockTags.register("fence_gates");
    public static final TagKey<Block> UNSTABLE_BOTTOM_CENTER = BlockTags.register("unstable_bottom_center");
    public static final TagKey<Block> MUSHROOM_GROW_BLOCK = BlockTags.register("mushroom_grow_block");
    public static final TagKey<Block> INFINIBURN_OVERWORLD = BlockTags.register("infiniburn_overworld");
    public static final TagKey<Block> INFINIBURN_NETHER = BlockTags.register("infiniburn_nether");
    public static final TagKey<Block> INFINIBURN_END = BlockTags.register("infiniburn_end");
    public static final TagKey<Block> BASE_STONE_OVERWORLD = BlockTags.register("base_stone_overworld");
    public static final TagKey<Block> STONE_ORE_REPLACEABLES = BlockTags.register("stone_ore_replaceables");
    public static final TagKey<Block> DEEPSLATE_ORE_REPLACEABLES = BlockTags.register("deepslate_ore_replaceables");
    public static final TagKey<Block> BASE_STONE_NETHER = BlockTags.register("base_stone_nether");
    public static final TagKey<Block> CANDLE_CAKES = BlockTags.register("candle_cakes");
    public static final TagKey<Block> CAULDRONS = BlockTags.register("cauldrons");
    public static final TagKey<Block> CRYSTAL_SOUND_BLOCKS = BlockTags.register("crystal_sound_blocks");
    public static final TagKey<Block> INSIDE_STEP_SOUND_BLOCKS = BlockTags.register("inside_step_sound_blocks");
    public static final TagKey<Block> OCCLUDES_VIBRATION_SIGNALS = BlockTags.register("occludes_vibration_signals");
    public static final TagKey<Block> DRIPSTONE_REPLACEABLE_BLOCKS = BlockTags.register("dripstone_replaceable_blocks");
    public static final TagKey<Block> CAVE_VINES = BlockTags.register("cave_vines");
    public static final TagKey<Block> MOSS_REPLACEABLE = BlockTags.register("moss_replaceable");
    public static final TagKey<Block> LUSH_GROUND_REPLACEABLE = BlockTags.register("lush_ground_replaceable");
    public static final TagKey<Block> AZALEA_ROOT_REPLACEABLE = BlockTags.register("azalea_root_replaceable");
    public static final TagKey<Block> SMALL_DRIPLEAF_PLACEABLE = BlockTags.register("small_dripleaf_placeable");
    public static final TagKey<Block> BIG_DRIPLEAF_PLACEABLE = BlockTags.register("big_dripleaf_placeable");
    public static final TagKey<Block> SNOW = BlockTags.register("snow");
    public static final TagKey<Block> AXE_MINEABLE = BlockTags.register("mineable/axe");
    public static final TagKey<Block> HOE_MINEABLE = BlockTags.register("mineable/hoe");
    public static final TagKey<Block> PICKAXE_MINEABLE = BlockTags.register("mineable/pickaxe");
    public static final TagKey<Block> SHOVEL_MINEABLE = BlockTags.register("mineable/shovel");
    public static final TagKey<Block> NEEDS_DIAMOND_TOOL = BlockTags.register("needs_diamond_tool");
    public static final TagKey<Block> NEEDS_IRON_TOOL = BlockTags.register("needs_iron_tool");
    public static final TagKey<Block> NEEDS_STONE_TOOL = BlockTags.register("needs_stone_tool");
    public static final TagKey<Block> FEATURES_CANNOT_REPLACE = BlockTags.register("features_cannot_replace");
    public static final TagKey<Block> LAVA_POOL_STONE_CANNOT_REPLACE = BlockTags.register("lava_pool_stone_cannot_replace");
    public static final TagKey<Block> GEODE_INVALID_BLOCKS = BlockTags.register("geode_invalid_blocks");
    public static final TagKey<Block> ANIMALS_SPAWNABLE_ON = BlockTags.register("animals_spawnable_on");
    public static final TagKey<Block> AXOLOTLS_SPAWNABLE_ON = BlockTags.register("axolotls_spawnable_on");
    public static final TagKey<Block> GOATS_SPAWNABLE_ON = BlockTags.register("goats_spawnable_on");
    public static final TagKey<Block> MOOSHROOMS_SPAWNABLE_ON = BlockTags.register("mooshrooms_spawnable_on");
    public static final TagKey<Block> PARROTS_SPAWNABLE_ON = BlockTags.register("parrots_spawnable_on");
    public static final TagKey<Block> POLAR_BEARS_SPAWNABLE_ON_IN_FROZEN_OCEAN = BlockTags.register("polar_bears_spawnable_on_in_frozen_ocean");
    public static final TagKey<Block> RABBITS_SPAWNABLE_ON = BlockTags.register("rabbits_spawnable_on");
    public static final TagKey<Block> FOXES_SPAWNABLE_ON = BlockTags.register("foxes_spawnable_on");
    public static final TagKey<Block> WOLVES_SPAWNABLE_ON = BlockTags.register("wolves_spawnable_on");
    public static final TagKey<Block> AZALEA_GROWS_ON = BlockTags.register("azalea_grows_on");
    public static final TagKey<Block> REPLACEABLE_PLANTS = BlockTags.register("replaceable_plants");

    private BlockTags() {
    }

    private static TagKey<Block> register(String id) {
        return TagKey.intern(Registry.BLOCK_KEY, new Identifier(id));
    }
}

